ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT ON TABLES FROM scorearc_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT, INSERT, UPDATE ON TABLES FROM scorearc_ingester;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE USAGE ON SEQUENCES FROM scorearc_ingester;

DROP TABLE IF EXISTS top_scorer;
DROP TABLE IF EXISTS standing;
DROP TABLE IF EXISTS match_detail;
DROP TABLE IF EXISTS match;
DROP TABLE IF EXISTS team;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT ON TABLES FROM scorearc_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT, INSERT, UPDATE ON TABLES FROM scorearc_ingester;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE USAGE ON SEQUENCES FROM scorearc_ingester;
DROP ROLE IF EXISTS scorearc_ingester;
DROP ROLE IF EXISTS scorearc_reader;
